/*
 * Roster Servise API
 *
 * This is TEST API for my service
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Equipment struct {
	// ID equipment
	Id string `json:"id"`
}
