/*
 * Roster Servise API
 *
 * This is TEST API for my service
 *
 * API version: 0.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Unit struct {
	// ID unit
	Id string `json:"id"`

	Equipments []Equipment `json:"equipments"`
}
